### ISSUE TITLE
Youtube video cannot be included in playlist

### ISSUE THREAD

**Issue by platisd** [DIT112-V21/group-18#34]
Hi,
Can you please remove the Youtube kids feature from your video? It becomes harder to embed and add to playlist 😱

**Comment by alynnka** [comment]
Modified from "Yes, it's Made for kids" to "No, it's not Made for kids".

**Comment by platisd** [comment]
Thanks! The "made for kids" term is a bit misleading on YouTube. It's more like "would kids be interested in it" :P
